### ISSUE TITLE
List has no update or get attribute

### ISSUE THREAD

**Issue by CyclonesStuff** [Arimuon/erlcPY#5]
Getting this error when running simple code found in the introduction. I get the error 'list' has no attribute 'update'. After changing this, I also get 'list' has no attribute 'get'.
![image](https://github.com/Arimuon/erlcPY/assets/92407262/4cb8dfc5-46d1-4ba0-ad14-2b7751c10e50)

**Comment by Arimuon** [comment]
Can I ask which example code you ran?

**Comment by CyclonesStuff** [comment]
.

**Comment by Arimuon** [comment]
** !! You will need to reset your server key now because you leaked it !!**, I recreated your code and made some corrections, then **later today I will publish a fix for the function** `_make_request`  _(which is inside of erlcPY)_, this will fix the `List has no update or get attribute` error. **Please update your version of erlcPY once I publish the update then used this corrected code.*
_I'll let you know when the update is published._

``py
from erlcpy import Information

# Define your API credentials
base_url = "https://api.policeroleplay.community/v1" # !! Never change this !!
server_key = "your_server_key" # API key from a ER:LC server
global_api_key = "your_global_key" # !! Remove if unnecessary !!

# Assuming base_url and server_key are already defined
info_api = Information(base_url, server_key)  # Add global_api_key if necessary

try:
    # Retrieve the players information from the server
    players_info = info_api.get_players()

    # Check if the response is not None
    if players_info:
        print("Players information:")
        for player in players_info:
            print(player)  
    else:
        print(f"Failed to retrieve players information.")
except Exception as e:
    print(f"An error occurred: {e}")
``

**Comment by Arimuon** [comment]
**!! You will need to reset your server key now because you leaked it !!**, I recreated your code and made some corrections, then **later today I will publish a fix for the function** `_make_request`  _(which is inside of erlcPY)_, this will fix the `List has no update or get attribute` error. 
**Please update your version of erlcPY once I publish the update then use this corrected code.**
_I'll let you know when the update is published._

```python
from erlcpy import Information

# Define your API credentials
base_url = "https://api.policeroleplay.community/v1" # !! Never change this !!
server_key = "your_server_key" # API key from a ER:LC server
global_api_key = "your_global_key" # !! Remove if unnecessary !!

# Assuming base_url and server_key are already defined
info_api = Information(base_url, server_key)  # Add global_api_key if necessary

try:
    # Retrieve the players information from the server
    players_info = info_api.get_players()

    # Check if the response is not None
    if players_info:
        print("Players information:")
        for player in players_info:
            print(player)  
    else:
        print(f"Failed to retrieve players information.")
except Exception as e:
    print(f"An error occurred: {e}")
```

**Comment by Arimuon** [comment]
Updated was released.
